library(httr)
library(httpuv)
oauth_endpoints("github")
myapp <- oauth_app("github", key = "f0d3ce43bf8833d5c3db", secret = "4fab5de309246d3efc266546d28027d4df734373")
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
gtoken <- config(token = github_token)
req <- GET("https://api.github.com/users/jtleek/repos/content.json", gtoken)
stop_for_status(req)
req1 <- content(req)
req2 <- jsonlite::toJSON(req1)
req3 <- jsonlite::fromJSON(req2)